CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "description" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "password" varchar,
  "phone" integer UNIQUE,
  "email" varchar UNIQUE,
  "role_id" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "employees" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "role_id" bigint,
  "status" bool DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "days" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "description" text,
  "start_at" time,
  "end_at" time,
  "status" bool,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "services" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar,
  "name" varchar,
  "estimated_time" time,
  "status" bool DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "appointments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_at" datetime,
  "end_at" datetime,
  "day_id" bigint,
  "user_id" bigint,
  "employee_id" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "appointment_services" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" bigint,
  "appointment_id" bigint
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "employees" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("day_id") REFERENCES "days" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");

ALTER TABLE "appointment_services" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("id");

ALTER TABLE "appointment_services" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");
